# SPDX-License-Identifier: GPL-2.0-only
# FPLinux armv7 package policy. Do not inherit x86_64 Alpine compiler flags.
CPPFLAGS="-D_FORTIFY_SOURCE=2"
CFLAGS="-Os -pipe -mcpu=cortex-a7 -mfpu=vfpv4 -mfloat-abi=hard -fstack-protector-strong -Wformat -Werror=format-security"
CXXFLAGS="$CFLAGS"
LDFLAGS="-fuse-ld=lld -Wl,--build-id=none -Wl,--as-needed -Wl,-z,relro,-z,now"
PACKAGER="FPLinux contributors <fplinux@example.invalid>"
