# SPDX-License-Identifier: GPL-2.0-only
# devtmpfs owns /dev. Without a matching rule mdevd would create device nodes
# as root:root 0660, so match every uevent without creating, changing or
# removing a node and without running a command. mdevd then only rebroadcasts.
.* 0:0 0600 !
