[kern]
version = "0.9.3"
archive_url = "https://github.com/getkern/kern/releases/download/v0.9.3/kern-x86_64-unknown-linux-musl.tar.gz"
archive_sha256 = "4dd31be2935a95c8cb842cbe11b7163d2799b3c83bf0aec582fb30209f3ffe27"
binary_sha256 = "77afff3515251eb2c396b3e12383dba3f180a7b69a42a52831c111b48eef66bc"

[oci]
repository = "localhost/fplinux-build"
platform = "linux/amd64"
base_repository = "localhost/fplinux-alpine-base"
base_release = "3.24.1"
base_rootfs_url = "https://dl-cdn.alpinelinux.org/alpine/v3.24/releases/x86_64/alpine-minirootfs-3.24.1-x86_64.tar.gz"
base_rootfs_sha256 = "41f73e3cf5fa919b8aa5ca6b30dc48f0da2720776d7423e2a7748211456fe081"
