[kern]
version = "0.30.1"
archive_url = "https://github.com/getkern/kern/releases/download/v0.30.1/kern-x86_64-unknown-linux-musl.tar.gz"
archive_sha256 = "2bcf2db24095c037db22e2f4dc4156f5112313d8c2a5b80e520e62745761f044"
binary_sha256 = "3bf0707ec6b083ffee943bd8fe89ac0d3ea28851b5504cb92156b997c7b4b9a8"

[oci]
repository = "localhost/fplinux-build"
platform = "linux/amd64"
base_repository = "localhost/fplinux-alpine-base"
base_release = "3.24.2"
base_rootfs_url = "https://dl-cdn.alpinelinux.org/alpine/v3.24/releases/x86_64/alpine-minirootfs-3.24.2-x86_64.tar.gz"
base_rootfs_sha256 = "c5ca053cfe1d85c5b96dff8b9bc57045f7f184a30ffb6b65776409ca90388677"
