version = 1
SPDX-PackageName = "FPLinux"
SPDX-PackageSupplier = "FPLinux contributors"

[[annotations]]
path = [
  ".cache/.fplinux-workspace",
  ".clang-format",
  ".kernignore",
  ".editorconfig",
  ".gitattributes",
  ".githooks/**",
  ".gitignore",
  ".markdownlint-cli2.jsonc",
  ".prettierignore",
  ".prettierrc.json",
  ".vale.ini",
  "Containerfile",
  "LICENSE",
  "README.md",
  "REUSE.toml",
  "alpine.lock.toml",
  "alpine/**",
  "THIRD_PARTY_NOTICES.md",
  "_typos.toml",
  "bootstrap/**",
  "commitlint.config.mjs",
  "common/**",
  "container.lock.toml",
  "docs/**",
  "fplinux",
  "package-lock.json",
  "package.json",
  "platforms/**",
  "pyproject.toml",
  "releases.lock.toml",
  "scripts/**",
  "sources.lock.toml",
  "targets/**",
  "tests/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 FPLinux contributors"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = "alpine/aports/fplinux-tyrquake/*.patch"
precedence = "override"
SPDX-FileCopyrightText = "2026 FPLinux contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "THIRD_PARTY_LICENSES/musl/COPYRIGHT"
precedence = "override"
SPDX-FileCopyrightText = "2005-2020 Rich Felker, et al."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "platforms/ums9117/bootstrap/ums9117-linux.ld"
precedence = "override"
SPDX-FileCopyrightText = "fpdoom contributors"
SPDX-License-Identifier = "Unlicense"
