/* SPDX-License-Identifier: MIT */
#ifndef MICROPY_INCLUDED_FPLINUX_MPCONFIGVARIANT_H
#define MICROPY_INCLUDED_FPLINUX_MPCONFIGVARIANT_H

#define MICROPY_CONFIG_ROM_LEVEL (MICROPY_CONFIG_ROM_LEVEL_EXTRA_FEATURES)
#include "../mpconfigvariant_common.h"

#endif
