# SPDX-License-Identifier: MIT
FROZEN_MANIFEST ?= $(VARIANT_DIR)/manifest.py

MICROPY_USE_READLINE = 0
MICROPY_PY_BTREE = 0
MICROPY_PY_THREAD = 1
MICROPY_PY_THREAD_GIL = 1
MICROPY_PY_FFI = 0
MICROPY_PY_SSL = 0
MICROPY_SSL_MBEDTLS = 0
MICROPY_PY_JNI = 0
MICROPY_VFS_FAT = 0
MICROPY_VFS_LFS1 = 0
MICROPY_VFS_LFS2 = 0
