# SPDX-License-Identifier: GPL-2.0-only
# Convert application PCM to the formats supported by the phone's audio device.
pcm.!default {
	type plug
	slave {
		pcm "hw:0,0"
		rate 48000
	}
}

ctl.!default {
	type hw
	card 0
}
