#!/sbin/openrc-run
# SPDX-License-Identifier: GPL-2.0-only
# shellcheck shell=sh disable=SC2034

name="FPLinux USB DHCP server"
description="Configure the host on the USB network"
supervisor=supervise-daemon
command=/bin/busybox-extras
command_args="udhcpd -f /run/fplinux-udhcpd.conf"
input_file=/dev/null
output_logger="/usr/libexec/fplinux/kmsg --level 6 --tag fplinux-usb-dhcp"
error_logger="/usr/libexec/fplinux/kmsg --level 4 --tag fplinux-usb-dhcp"
respawn_delay=1
respawn_max=3
retry="TERM/2/KILL/2"

depend() {
	need fplinux-usb-gadget
}

start_pre() {
	[ -f /run/fplinux-udhcpd.conf ] || return 1
	checkpath -f -m 0600 /run/fplinux-udhcpd.leases
}
