# SPDX-License-Identifier: GPL-2.0-only
override NAME := maxvi_k15n_4g_linux_bootstrap
override FPLINUX_BOOTSTRAP_DTB := maxvi_k15n_4g.dtb
override FPLINUX_BOOT_FONT := 7x14

include ums9117-bootstrap/bootstrap.make
