# SPDX-License-Identifier: GPL-2.0-only
override NAME := inoi244_linux_bootstrap
override FPLINUX_BOOTSTRAP_DTB := inoi244.dtb
override FPLINUX_BOOT_FONT := 7x14

include ums9117-bootstrap/bootstrap.make
