# SPDX-License-Identifier: GPL-2.0-only
override NAME := inoi240_linux_bootstrap
override FPLINUX_BOOTSTRAP_DTB := inoi240.dtb
override FPLINUX_BOOT_FONT := 6x8

include ums9117-bootstrap/bootstrap.make
