/* SPDX-License-Identifier: MIT */
#ifndef FPLINUX_DROPBEAR_LOCALOPTIONS_H
#define FPLINUX_DROPBEAR_LOCALOPTIONS_H

#define INETD_MODE 0
#define DROPBEAR_SVR_PASSWORD_AUTH 0
#define DROPBEAR_SVR_PAM_AUTH 0
#define DROPBEAR_SVR_LOCALTCPFWD 0
#define DROPBEAR_SVR_REMOTETCPFWD 0
#define DROPBEAR_SVR_LOCALSTREAMFWD 0
#define DROPBEAR_SVR_REMOTESTREAMFWD 0
#define DROPBEAR_SVR_AGENTFWD 0
#define SFTPSERVER_PATH "/usr/lib/ssh/sftp-server"

#endif
