# SPDX-License-Identifier: GPL-2.0-only
override NAME := ta1618_linux_bootstrap
override FPLINUX_BOOTSTRAP_MODE := linux
override FPLINUX_BOOTSTRAP_DTB := ta1618.dtb

include ums9117-bootstrap/bootstrap.make
