/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef _DT_BINDINGS_CLOCK_FPLINUX_UMS9117_INHERITED_CLK_H
#define _DT_BINDINGS_CLOCK_FPLINUX_UMS9117_INHERITED_CLK_H

#define FPLINUX_UMS9117_CLK_MPLL 0
#define FPLINUX_UMS9117_CLK_CA7_CORE 1
#define FPLINUX_UMS9117_CLK_NUM 2

#endif
